version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.4

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:erbium

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run-script code-format-check && npm test

      - coveralls/upload

      - store_artifacts:
          path: coverage
